### ISSUE TITLE
[Feature request] Linux/non-Windows OS support.

### ISSUE THREAD

**Issue by sirocyl** [BleuBleu/FamiStudio#1]
From what I've seen of people trying it out, it isn't working well under Linux, either with Wine or Mono. I haven't tested this myself yet, but having functional Linux support would open things up to a wider audience.

Being that this is in C# for the most part, making the necessary changes could be a realistic goal.

**Comment by BleuBleu** [comment]
Ha yes.

A got a some of request for that on twitter. 

This might be doable, but it will require a lot of work, and performance on these platform might be really bad. 

As you said, it is a C# project, but it sits on top of Direct2D (which is essentially a wrapper around D3D11) and XAudio2, which are definitely Microsoft-centric technologies. To achieve a port, I think (although I am not sure) I might have to go back to GDI-style graphics, which are terribly slow and more old-school wave-out for audio.

If you have any insight on these, please let me know. I will keep the request open since a lot of people asked for it.

-Mat

**Comment by Wolf480pl** [comment]
>I might have to go back to GDI-style graphics, which are terribly slow

Maybe you could use something like [skia] or [cairo] instead?

[skia]: https://skia.org/
[cairo]: https://www.cairographics.org/

**Comment by BleuBleu** [comment]
Yes I've been reading a bit. Cairo is definitely a good match, it's feature set is very similar to D2D. Do you happen to know an audio library that is similar to XAudio2?

**Comment by sirocyl** [comment]
I was looking at BambooTracker, and it seems to use Qt/QAudio from the Qt multimedia libraries for its audio. That seems reasonably cross platform, too. I don't think you need the whole of Qt for it either.

See: https://github.com/rerrahkr/BambooTracker/blob/master/BambooTracker/stream/audio_stream.cpp

**Comment by BleuBleu** [comment]
Oh that looks good. I could probably wrap this in a dll somehow and call it from c#. Thanks for the info.

**Comment by atsushieno** [comment]
If you use [SkiaSharp](https://github.com/mono/skiasharp) it's quite portable to almost everywhere. Or if you want to stick to DirectX approach then [MonoGame](https://github.com/MonoGame/MonoGame) might be useful, which is basically XNA alike.

**Comment by BleuBleu** [comment]
Thanks man. 

Seems like there are lot of options for graphics. I'll do more research on the 2 you sent. Ideally I'd prefer to pick an API that is more 2D centric and doesn't require writing any shaders (D2D creates the D3D11 shaders behind the scene). That's why Cairo was attractive, it's essentially the same as D2D.

Audio seems to be more limited in Mono. MonoGame does have audio support, but it seems a bit overkill to use this big framework for such a small part. There has to be a simple Mono/portable audio framework around. 

-Mat

**Comment by atsushieno** [comment]
I have once created [https://github.com/atsushieno/libsoundio-sharp] but it might be quite tricky to get used to it (I had trouble finding out audio glitches from my app). Similarly created portaudio-sharp but didn't really use it.

On the other hand my [managed-midi](https://github.com/atsushieno/managed-midi) is fairly easy to use.

**Comment by BleuBleu** [comment]
What is hard to get used to your lib? My audio usage is extremely minimal. I create 1 voice (or streams whatever is your nomenclatures), send samples to it. That is it. I don't need anything fancy. If it can do that in a portable way, im sold! :)

-Mat

**Comment by atsushieno** [comment]
TBH I haven't investigated much on that, but the annoyance was from debugging native callbacks that often result in crashes where no managed debuggers help (on Linux). If you just play simple non-streaming audio data then a friend dev. wrote a simple player code around it. https://qiita.com/tan-y/items/0248c5e3f6cbd42b1370 (sorry but it is a Japanese page, code would be still readable).

**Comment by jimbo1qaz** [comment]
bambootracker had poorly designed threading, and UI freezes would make audio engine/synth/output stop playing. Since the merge of https://github.com/rerrahkr/BambooTracker/pull/152 , they switched from Qt event loop and audio to RtAudio.

**Comment by BleuBleu** [comment]
Next version will have macOS support. Im waiting for Catalina to come out to do my final testing. It is based around OpenTK (OpenGL) for the main window. Some of the dialogs are going to be GTK# (which is super old tech, but I have very few dialogs). It uses PortAudio for the sound. 

This (in theory) will make it possible to port to Linux as well with minor tweaks. I don't have an ETA for that tho. I likely will be busy on other stuff in the coming months.

**Comment by BleuBleu** [comment]
macOS support was added in 1.2.0. Linux I will only do if I find a charitable soul that wants to help.
