### ISSUE TITLE
Confusing / wrong use of term "Note" for song properties.

### ISSUE THREAD

**Issue by nezvers** [BleuBleu/FamiStudio#13]
I'm talking about - "Frames per Note", "Notes per pattern" and "Notes per bar".
In the "Frames per Note" and "Notes per bar" word Note refers to 1/4th note, which probably would be better to use word "Beat".
"Frames per Note" refers to 1/16th note, dunno what term would be better for it but at the current situation word, "Note" is used for 2 different meanings.

**Comment by BleuBleu** [comment]
Hi!

I encourage you to check the tutorial. This is emulating what the real NES hardware does. Real hardware has no notion of beats, all it does it run at 60 FPS, and you have the opportunity to change the sound every frame.

[Tutorial](https://youtu.be/-5GovfMwF90)

I have no plan to abstract this. If you want accurate NES sound, you will have to learn a little bit how it works at the low level unfortunately..

-Mat

**Comment by N-SPC700** [comment]
It would still be gramatically correct to use "beat" instead of "note". Updating every frame for 60 frames is just a 750BPM song. The NES/Famicom hardware isn't even limited to the frames of the region it's in, you can go well past the common 60Hz sound driver speed, into ranges where raw PCM is possible (8000hz, up to 16000hz max). The real limit is just the CPU's speed itself.
