### ISSUE TITLE
Broken FTM Compatibility (& some more issues and feature requests)

### ISSUE THREAD

**Issue by N-SPC700** [BleuBleu/FamiStudio#14]
Exactly what it says on the tin. The ability to open FTMs does work, but many _many_ commands don't work, and some songs straight up just don't sound right at all, due to the lack of feature implementation. Take for example, the Namco 163's wave switching. That's not possible here, and some imported songs suffer hard. Same applies to manual VRC6 pulse width commands. Additionally, some DPCM samples don't even import.

Other Issues:
- iNES ROM export stutters occasionally.
- Said export doesn't export used expansion chip(s). Not a surprise, as each one has it's own quirks, and one of them (5B/FME-7), isn't even emulated right. Additionally, there could be something similar to [this](https://www.youtube.com/watch?v=iDK-1ZX5KoA), where it uses the CPU to simulate the extra channels in software, but that requires that there is no DPCM being used at the same time.
- Opening some FTM modules straight up break the program into a "unhandled exception" which persists until the program is terminated. [Link to the module.](https://github.com/BleuBleu/FamiStudio/files/4572393/open.this.to.break.famistudio.zip)

- Most of the mixing for the soundchips is inaccurate.
- This one's already known, but the 5B is lacking it's extra features (envelope+tone)
- From my tests, PAL 2A07 mode lacks the extra low notes (G#0 and a detuned G-0), compared to the default A#0 and A-0.
- Stereo isn't a feature of the NES/Famicom hardware. No official NES/Famicom system has any stereo capabilities, however unofficial systems like certain VT03 soundchip revisions or the Generation NEX do support stereo.

Feature Requests (not necessary but would be great to have):
- Famitracker Text Import
- Famitracker-Styled interface, similar to [this suggestion](https://github.com/BleuBleu/FamiStudio/issues/9)
- Possible NES .dmf module compatibility (quite unlikely, though.)
- 7-bit/MMC5 PCM
- Nonstandard 60Hz refresh rates (with working ROM export)
- Backwards compatibility mode (for modules made in Pre-2.0 Famistudio.)
- VT03 or 2x2A03 soundchip mode
- .0CC file support

Additionally, do you have any plans for sample songs that are made by the users, if they are covers/originals/recreations? I think both me and quite a few people would be interested in adding a few sample songs to future versions.

**Comment by BleuBleu** [comment]
Hi! This is a huge post. I will read it one night this week, I have some crashes to address that will take higher priority. Thanks for you patience, i appreciate the feedback.

-Mat

**Comment by sirocyl** [comment]
In the future, when you submit issues, I'd recommend itemizing out individual issues/requests, so that they can be triaged, workflowed and tackled independently. I've seen people being banned from issue trackers for laundry-listing multiple points in a single issue, and it's more proper Github etiquette. 🙂

**Comment by N-SPC700** [comment]
Yeah, my bad. Sorry about that :P

**Comment by BleuBleu** [comment]
Hi!

Finally have some time to catch up on this! I dont think ill be able to address everything that is in the post, Apologies in advance for the long post! :) 

I'll cover the ones I think are important, so if i dont cover a topic, assume its not a priority at the moment. 

Here is roughly how I chooses to add new features or not, just so you understand where im coming from.

1.  I am not interested in features that are too _tracker-centric_: There are tons of trackers out there, im doing something else. (ex: delayed cuts/stops will be considered low priority).
2. I want to avoid feature duplication: If there is a reasonable alternative right now, the feature will not be very important to me, lean and mean is the key here. (ex: Vxx, creating a new instrument and copying the envelopes take 3 seconds). 
3. I want to prioritize features that benefits the most people (ex: Linux port and giving people using trackpad better controls will take precedence over some obscure expansion chip that was rarely used).

Rant over! Let's break it down:

**Broken FTM compatibility.**

I think i've been very transparent from the trailer and the documentation (which i assume you have checked out) that only a subset of features are supported.

![image](https://user-images.githubusercontent.com/6654334/81064146-bc9c6600-8f0b-11ea-93ab-80ae8aa32738.png)

There is extensive coverage of the limitations in the doc:

- https://famistudio.org/doc/importexport/#famitracker-text
- https://famistudio.org/doc/importexport/#famitracker-text-or-binary

I'll post a snipped here, but there is a lot more info in the doc (such as you N163 comment, all well documented).

> Note that only a small subset of features is supported. Only the following effects are supported. Every other effect will be ignored:

    1xx/2xx (Slide up/down) : Will be converted to slide notes
    3xx (Portamento) : Will be converted to slide notes.
    4xy (Vibrato) : Vibrator speed will be slightly modified, see table above for mapping.
    Bxx (Jump) : Will be converted to loop point.
    Dxx (Skip) : Will be converted to a custom pattern length.
    Fxx (Speed) : Only speed is supported.
    Pxx (Fine pitch) : Fully supported.
    Hxx (FDS Modulation depth) : Fully supported.
    Ixx/Jxx (FDS Modulation speed) : Fully supported, but combined in one 16-bit value.

DPCM samples that dont load is likely because they go over the 16KB limit, which i have no interest in expanding in the short term.

**ROM studder**

I am very interested in fixing this, would it be too much to ask too send me the song so I can debug?

**Crash when importing FTM**

Thanks so much for attaching the file, this is how you report a bug, A+! Next version will have the fix. In the meatime, make sure all your song names are unique in the file (they are all called "New song" at the moment and this confuses the app very much).

**Missing 5B feature** 

Yes, it is mentioned in the limitations on the website as well. I use emu2149 for the audio generation, so in theory it wouldnt be too hard to expand. I am definitely intrigued to see how this chip could sound, but definately low priority imho.

**PAL 2A07**

The APU pulse period is also 11-bit on PAL. I dont think you can go lower than G#0 (roughly). Please correct me if i am wrong.

https://wiki.nesdev.com/w/index.php/APU_Pulse

**Stereo** 

Would be cool but kind of low priority. 

**FamiTracker text import/export**

Been supported since 1.1.0 (August 2019), was covered in multiple tutorials (https://youtu.be/-5GovfMwF90), documentation, etc.

**Backward compatibility**

Files made all the way back from FamiStudio 1.0.0 are supported. If you have an example that does not work, please send it to me. This is _extremely_ important to me, I never want to break compatibility, ever.

**Demo songs**

Yes! Please, if you want to get involved an contribute a demo song, i would love that. I'll give you full credit, feature it in a trailer if it fits the tone. 

-Mat

**Comment by sirocyl** [comment]
I very much appreciate the attention to detail, extensive documentation, and a sharp focus on usability, reliability and compatibility - all while maintaining simplicity, elegance and speed - and especially the clear and goal-oriented development methodology moving forward! This is an exciting and important project to a lot of people, and I can see that it is being handled incredibly well. <3

Honestly, this project is rather ambitious, and I didn't expect for it to pick up so quickly and exceed all my expectations. As much as I usually prefer and admire a tracker UI for composition, I'd say this might easily be the best tool for NES chiptune to date, and one of the better utilities for chiptune in general.

And I run a Famitracker [fan site](https://famitracker.org) and community.

**Comment by BleuBleu** [comment]
Thanks for understanding where I am coming from. I hope OP replies so the discussion can resume. 

-Mat

**Comment by BleuBleu** [comment]
The FTM crash due to duplicate song names in included in 2.0.2 which was just released. OP has not followed up on any of the other topics. Closing.
