### ISSUE TITLE
Issue on NSF export

### ISSUE THREAD

**Issue by KLONOA9X6** [BleuBleu/FamiStudio#144]
This is what I did.
[project.zip](https://github.com/BleuBleu/FamiStudio/files/9224190/project.zip)
This is what I exported.
[export.zip](https://github.com/BleuBleu/FamiStudio/files/9224196/export.zip)
Why the FDS channel speed is faster?
(Version 3.3.1)

**Comment by BleuBleu** [comment]
Thanks for the files. I will test this tomorrow!

-Mat

**Comment by BleuBleu** [comment]
So i took a look and you are right, something is wrong. 

The good news is that the issue seems fixed in the development version (4.0.0). I'm hoping to release it in about a 4-6 weeks. If you want to get an early beta, come see us on Discord and I will start looking for beta tester in a couple weeks.

Nice little tune. 

-Mat

[moon400.zip](https://github.com/BleuBleu/FamiStudio/files/9227938/moon400.zip)

**Comment by KLONOA9X6** [comment]
Thank you so much.

**Comment by jadasse** [comment]
I am also having this issue, glad to see it being worked on.

**Comment by BleuBleu** [comment]
Fixed 4.0.0.
