### ISSUE TITLE
Pan on scroll; and add 2-dimensional scroll-wheel support.

### ISSUE THREAD

**Issue by sirocyl** [BleuBleu/FamiStudio#16]
I'm aware that you can pan the document by holding ALT and clicking/dragging the pattern editor, but with some input devices, especially laptops, that becomes tedious when editing larger documents.

### The tl;dr:
1. Add X/Y scroll support, for those mice and trackpads that have it and support it, including the Apple Magic Mouse. Scrolling left+right should always pan left or right.
2. Also add an option to prioritize panning on scroll over zoom on scroll (holding CTRL would switch to zoom mode.)

#### The backstory:
I generally use a laptop for composition work, a Thinkpad - the model isn't as important, but bear in mind that it has two mouse inputs, which IBM/Lenovo call an "UltraNav", both of which aren't traditional:
1. **A multi-touch trackpad, with a "one-button"/virtual left/middle click design.** Like most modern laptops, it has a capacitive trackpad which can operate the cursor, and click, with both taps and a physical press, which simulates a right mouse button click when you tap or press in a certain zone of the pad.
2. **The TrackPoint™ pointing-stick device.** Also known as "the nipple" or various [less-than-savory](https://xkcd.com/243/) terms, it is given three physical buttons - the left and right function as expected, but the middle is special.

The TrackPoint takes priority over the touchpad, if both are being manipulated.

On Windows, as default, the TrackPoint middle button is used to momentarily switch from "pointing mode" to "scrolling mode" for the duration that the button is pressed. It cannot typically operate as a middle-click/3rd mouse button.

When in scroll mode, the Trackpoint acts as an x/y scroll wheel, moving the document or page under the cursor, but not moving the cursor. Depending on how much pressure you put in either direction, it fires many scroll events, which most browsers and page readers smooth out, but a lot of applications either slowly crawl a few pixels at a time, or (in FamiStudio's case) jump around like mad.

#### The problem:
When editing a FamiStudio document on a laptop, I find myself regularly zooming the page without realizing, and often losing my place in the page, when I mean to scroll/pan the pattern or piano roll view. While it would be more intuitive on a desktop with a proper three-button mouse, on a notebook there's a bit of a usability disconnect there.

#### The environment:
Lenovo ThinkPad with UltraNav/TrackPoint style 3-button pointing device. Also tested on other laptops with Synaptics brand touchpads/trackpads with multi-finger scroll.

### Example:
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/944067/81155992-8387e400-8f53-11ea-82f3-eb0dac1cc994.gif)

**Comment by BleuBleu** [comment]
Hi!

Yes, I've had tons (tons = more than 5 in our little chiptune community!) of people telling me that its impossible to use on a trackpad. The app definitely was not designed with that in mind. To be honest i am quite blown away that people manage to be productive with a trackpad/niplle, but heh, that might just be my lack of skills :)

I'll definitely put that on the list for 2.1.0. You explained the problem very well. 

Would you happen to be aware of an app (any, but best would be it if is music-related) that actually has decent trackpad control so I can look at it for inspiration and get a feel for what would be the best solution ?

-Mat

**Comment by sirocyl** [comment]
To answer your one question: Firefox.

Apologies in advance if the following is a bit disjointed, it's 5AM and I did quite a bit of traveling the night before. Anyway:
### Some implementation notes:
- **Use firefox, or a web browser, as a model** for scroll behavior.
- Be aware that the dominant, or "major" axis in a timeline document like FamiStudio, is horizontal in nature. **Scroll wheels should target the dominant axis.**
- Add settings for:
    - :ballot_box_with_check: Swapping the up/down scroll axis from the major to the cross axis.
    - :level_slider: Zoom speed/zoom step size.
- Use CTRL+vertical scroll to zoom in and out.
- Use SHIFT+vertical scroll to scroll horizontally, regardless of X-scroll capability on pointing device.
- X+Y scroll events can happen simultaneously, and should pan across the document with full range of motion, as expected - rather than constraining to X or Y at a time.

### the why:
Mozilla Firefox handles scroll and zoom behavior well with trackpad and trackpoint, and would serve as a good model for this. Scroll in either x/y direction scrolls the content; ctrl+scroll performs a zoom.

I've never used FL Studio with a trackpad or trackpoint, so I can't vouch for its handling of either. I just tested Audacity under Linux, and - while it's timeline based, it uses left/right scrolling to scroll forward and backwards through the document, so I wouldn't recommend emulating its behavior. I'm not sure offhand if it handles that better on Windows or not.

The main difference in FamiStudio, is that the major axis - i.e., the one which moves through the document rather than across its parameters - is horizontal in nature. It might be worth considering a settings :ballot_box_with_check: box to swap the scroll axis, so that users with X/Y scroll can scroll natively, but users with Y-only scroll will sweep across the timeline when scrolling, and not up and down the instruments/piano roll octaves.

### keep in mind:
- You may want to quantize or relax the zoom speed, in the event that one trackpad fires a ton of scroll events in quick succession. Perhaps provide a slider in the settings, that makes the zoom step size smaller, and probably a slider of value *n* to coalesce *n* many scroll "steps" into a zoom step.
 - not everyone has X/Y scroll wheels, with horizontal scroll capability. Firefox uses shift+scroll to scroll left/right, in that case, and that behaviour may apply here.
- X and Y scrolling events are not exclusive of one another. You should ensure diagonal scrolling/panning is performable, rather than scrolling in steps of X then Y then X again.

**Comment by BleuBleu** [comment]
Hey Hi!

I finally have to time to look into this. I was wondering if I could use you to test a prototype version of this. I do have 2 laptops with trackpads here, but no "nipple-type" control and I want to make sure not missing anything. Drop me an email at famistudio@outlook.com when you have some spare time. Thanks.

-Mat

**Comment by mmontag** [comment]
Just dropping by to add 2 cents:
- The issue is "what scrolling affordances should FamiStudio provide?"
- Shift+scroll wheel modifier for secondary-axis scrolling is super ubiquitous. It's implemented in the native "viewport" controls across all operating systems, for example. So we need that :)
- The middle-mouse-button click is nice to have, but difficult for me. It's clunky to press and hold while moving the mouse. You also have the problem that it takes multiple drags to get from one side to the other.
- And I'll state the obvious one, scrollbars. A bit outmoded by mouse wheels, but useful in a pinch.

**Comment by BleuBleu** [comment]
Thanks for the feedback man.

I've been thinking about it and where i am currently heading is to provide a simple "trackpad mode" control scheme in the setting which would swap a few controls :

- Mouse wheel would pan up/down instead of zooming. When swiping up/down on a trackpad, the OS sends a mouse wheel event. This gives very nice up/down smooth scrolling. 
- Horizontal mouse wheel would pan left/right. With a trackpad, this is a left/right swiping motion. As @mmontag suggested, Shift+Mousewheel could also do the same thing. Im totally cool with that.
- Control + Mouse wheel would zoom. When doing a "pinch-to-zoom" motion on a trackpad, this is what Windows will send to the app (need to check what Mac + Linux does actually, I hope its the same).
- I might also add other redundant buttons, things like Page Up + Page Down for zooming in/out (FL Studio has that) for people who needs more options. Not sure about that one.

Scroll bars I'd like to avoid. I draw all my own UI with D3D/OpenGL, i use no widget whatsoever, so adding that kind of stuff is actually a lot more work than it looks like unfortunately. :cold_sweat:

-Mat

**Comment by sirocyl** [comment]
Email sent.

I also have a mobile Windows XP/Vista/7 device with a resistive (one-point) touch screen and a "plain" pointing device - i.e., no scroll wheel - which I can test usability kinda stuff on.

**Comment by BleuBleu** [comment]
This was done in 2.1.0, needs to be enabled in the settings (Trackpad controls). 
Let me know if you have any further feedback.

**Comment by Incognito357** [comment]
shift+scrolling on linux still zooms instead of panning (not sure if that was actually added or just mentioned as a possibility)

**Comment by BleuBleu** [comment]
Have you enabled trackpad controls? Here on my disto it changes the scroll direction.

https://famistudio.org/doc/config/#user-interface-configuration

-Mat

**Comment by Incognito357** [comment]
Ah, no I guess I ignored it since I don't have a trackpad. Enabling this option makes the sequencer work as expected, allowing shift+scrolling to pan, and ctrl+scrolling to zoom, but takes away the ability to use the scrollwheel without ctrl held to zoom.

Shift or ctrl scrolling in the pattern editor is not consistent, though. Ctrl+scrolling seems to sporadically change between panning vertically and zooming, while shift+scrolling seems to change between panning vertically and horizontally. I feel like it thinks it hits a boundary of some kind, and prioritizes zooming or panning over the other temporarily, but it's hard to say exactly (it happens in the middle sometimes too). Overall, it seems to prioritize panning vertically over zooming or panning horizontally.

Scrolling normally (without holding ctrl or shift) in the pattern editor has the same issue referenced in https://github.com/BleuBleu/FamiStudio/issues/38, except the 2-tick jump happens for vertical panning rather than zooming (jumping between the extremes of the piano roll octaves).

Overall, using the trackpad option, the sequencer feels much more comfortable to use, but the pattern editor becomes much harder to use due to the inconsistencies (zooming becomes nearly impossible, but panning is still easy enough to use with middle click dragging).

Here I've recorded what happens, since it's a bit hard to explain. I am holding the buttons and scrolling the entire time, and tried to scroll up and down consistently. Sometimes it takes multiple scroll ticks before it responds as well, though that's hard to capture.

shift+scrolling:
![shift+scrolling](https://user-images.githubusercontent.com/433656/91185796-3f644f00-e6bc-11ea-810f-7574193cd77e.gif)

ctrl+scrolling:
![ctrl+scrolling](https://user-images.githubusercontent.com/433656/91185817-45f2c680-e6bc-11ea-879f-538e56422e6a.gif)
