### ISSUE TITLE
FamiStudio doesn't open on my Windows 7 SP1 laptop

### ISSUE THREAD

**Issue by cjrobe** [BleuBleu/FamiStudio#17]
Nearly fresh install with no further updates available in Windows update.

**Portable version:** double click EXE, no window ever pops up or task in task manager. If I right click and run as administrator, it gives a "FamiStudio has stopped working" window.

**Install version:** At first had the same symptom as portable version. Then when I reboot, starting FamiStudio from the start menu starts a Windows installer which hangs on the attached screen.

![Capture](https://user-images.githubusercontent.com/5606066/81244127-84feee00-8fdf-11ea-91dc-7366a337f491.PNG)

Since it mentioned .net updates, here's my list of .net versions from ASoft's tool.

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.2 General release (CLR:4.0)
.NET FW 4.7 General release (CLR:4.0)
.NET FW 4.7.1 General release (CLR:4.0)
.NET FW 4.7.2 General release (CLR:4.0)
.NET FW 4.8 General release (CLR:4.0)

Thanks and looking forward to trying the software! Let me know if there are any logs I can send you.

**Comment by BleuBleu** [comment]
Hi!

Thanks for the detailed report and sorry about the issue. I have setup a fresh Win7 machine and managed to reproduce the issue.

I have narrowed it down to some missing DLLs. These DLLs are included with Windows 8 and 10, but not 7 unfortunately.

**VS 2015 (x86) runtime**

This one you might already have since it was mentionned on the website, very easy to install, pick the x86 version if it asks: 
https://www.microsoft.com/en-pk/download/details.aspx?id=48145

**DirectX**

There are also some missing audio DLLs, the easiest fix is to install this (rather old) DirectX package and it will install the missing DLLs. 

This installer is a very clunky:
1. It is going to ask you to extra the files to somewhere, extract to a temporary folder
2. Run DXSETUP.exe inside that temporary folder to really install.
3. Delete the temp folder afterwards to cleanup.

https://www.microsoft.com/en-us/download/confirmation.aspx?id=8109

That being said, i could confirm it makes the app start, but I could not test the audio since I was connected to a remote machine. 

Could you report back to let me know how it goes?

If it fixes it, I will update the installation procedure on the website so that other people can learn from our issues.

-Mat

**Comment by cjrobe** [comment]
That DirectX setup did the trick, thanks! I remember that clunky setup, I always extract it to c:/dx out of habit. Look forward to exploring the software.

**Comment by cjrobe** [comment]
One more issue, at least on Windows 7.

I plugged in headphones after starting the program and FamiStudio did not switch over to playing from them until I restarted FamiStudio.

Vice versa, if I start it with plugged in headphones and unplug them, FamiStudio continues to attempt to output to the headphones and makes no sounds.
