### ISSUE TITLE
Add support for MUTIPLE audio expansions for ROM export

### ISSUE THREAD

**Issue by SopTheSop25B** [BleuBleu/FamiStudio#176]
Is it possible to add support for multiple audio expansions for ROM export for example: Songs with 2A03+FDS+MMC5+VRC6+VRC7+N163+S5B+EPSM

**Comment by BleuBleu** [comment]
Hi!

I would like to, but i think we have have a technical limitation here: To my knowledge, there are no mapper that can accommodate all these expansions. Basically, there were no physical cartridges that were ever made to support all that stuff. 

In real life, these expansions were made by different (competing) companies and some used the same memory ranges, etc. Its a mess. 

I'll close the bug since its technically impossible. If someone can prove me wrong, please reopen!

-Mat
