### ISSUE TITLE
Modifier keys not working on macOS?

### ISSUE THREAD

**Issue by mmontag** [BleuBleu/FamiStudio#25]
I'm unable to undo with hotkey (Cmd+Z) or add Stop Notes (Cmd+Click) or Release Notes (Shift+Click) in the piano roll.

I've tried on 2.0.1 and 2.0.2. Is it possible that the mouse modifier keys aren't being read correctly on macOS?

Catalina 10.15.4 (19E287)

**Comment by BleuBleu** [comment]
Hi! 

Thanks for getting in touch with me on that. I just have a single mac mini here so I cannot say i test a wide range of macOS devices. :)

Would you drop me an email at famistudio@outlook.com? I the best for us to diagnose this will be to get you a custom build that prints the keycodes of the keys you press in the console so I can see what's going on.

Thanks!

-Mat

**Comment by BleuBleu** [comment]
This issue was narrowed down to permissions in macOS. Will create a troubleshooting section in documention in case someone else has the same issue.

![image](https://user-images.githubusercontent.com/6654334/83344282-22c3af80-a337-11ea-85cf-4f3d7514a693.png)

Big thanks for the troubleshooting! Closing.
