### ISSUE TITLE
"Download file now?" helper prompt for downloading .NET 5.0 doesn't work properly

### ISSUE THREAD

**Issue by EdHerdman** [BleuBleu/FamiStudio#256]
I downloaded FamiStudio410-WinPortableExe yesterday and extracted it. Since I didn't have .NET 5 installed at the time, it offered a prompt with two options, one of which offers to download .NET. Clicking this did nothing on my installation other than close the prompt. Because of the prompt's wording, and the alternative "do nothing" option, I expected it to attempt to grab .NET 5.

I'm running Windows 11 Pro and Firefox is my default browser, in case this is a application default / protocol issue.

To be clear: I have fixed the issue by installing .NET 5.0 manually - this is not a help request.

**Comment by BleuBleu** [comment]
I'm not sure this is something i can control. This prompt is auto-generated and I wouldn't be surprised its broken. Ill do a quick googling and report back, but don't get your hopes up.

-Mat

**Comment by BleuBleu** [comment]
This appears to be a bug in older .NET versions and seems fixed in newer version. 

In the next hotfix, I will add a readme to the portable EXE version to explain the issue and give download links.

I'll keep the issue open until we migrate to a newer .NET and have a real fix, but that will not come soon.

-Mat

**Comment by BleuBleu** [comment]
Fixed 4.2.0.
