### ISSUE TITLE
FamiStudio refuses to export this as .nsf

### ISSUE THREAD

**Issue by LMPuny** [BleuBleu/FamiStudio#36]
i'm using famistudio's latest version and currently it refuses to export this to .nsf

i was doing various songs to export them as .nsf for a project, but famistudio refused to do so. then by excluding songs i discovered this one was faulty. i wondered if isolating it (copying seq. data to a new project, then selecting to import instruments) would export it but it still doesn't export.

https://dl.dropbox.com/s/6ng52wi32q4gxjw/doesnt_export_to_nsf.fms

**Comment by BleuBleu** [comment]
Hi!

Thanks so much for reporting this. This is indeed a real bug and I will definitely fix this. 

I do have a workaround for you in the meantime.

The issue is that in your song, some of the notes on the triangle channel don't have a valid instrument. I am not sure how that happened, you may have deleted an instrument at some point. Its currently impossible to see, since your "blank" instrument is gray, and gray also happens to also be the color i use for "invalid" instruments.

For fun, i changed the color of you blank instrument and it revealed the problematic notes, which remain gray.

![image](https://user-images.githubusercontent.com/6654334/89707601-4bed6580-d9a2-11ea-9650-a965f65cbc41.png)

Quick fix: Select this range of the song in the piano roll and drag you blank instrument over the notes to assign them an instrument and it will fix the song.

![SongFix](https://user-images.githubusercontent.com/6654334/89707631-8eaf3d80-d9a2-11ea-83e7-5c1ef5e1ae42.gif)

Apologies for the inconvenience.

-Mat

**Comment by LMPuny** [comment]
thanks for the answer! now it exports well, but now this one (which i isolated from the same project too) doesn't want to export despite not having any invalid instrument (i was wondering if i should have created a new issue for this since it's still related to the title)

https://dl.dropbox.com/s/1nbxxqhcw0uc5sw/doesnt_export_to_nsf_2.fms

**Comment by BleuBleu** [comment]
Wow you are NSF-bug finding machine! Thanks for stress-testing the system like this. I've exported some crazy songs to NSF, funny how you manage to break it with very simple songs.

This bug is definitely not something you can fix. I will debug some more on your own and will likely have to put a hotfix for it early next week once i figure out how to fix it.

-Mat

**Comment by BleuBleu** [comment]
FamiStudio 2.1.1 was just release and include the fix.

By the way, the tempo settings of your song is a bit all over the place. I would recommend tidying that up a bit :)

-Mat
