### ISSUE TITLE
Zooming in linux doesn't work as expected

### ISSUE THREAD

**Issue by Incognito357** [BleuBleu/FamiStudio#38]
Zooming normally with the scrollwheel in linux uses much larger jumps than expected. Scrolling goes from one extreme to the other extreme with only 2 clicks. Holding shift or control while scrolling makes zooming act as expected, with finer-grained steps between zoom levels (about 6 or 7 clicks to go to the extremes, depending on the part being zoomed). I would expect shift+scrolling to pan, and ctrl+scrolling to do larger jumps, while normal scrolling would perform the smaller zoom adjustments.

**Comment by Incognito357** [comment]
I've recorded what it looks like scrolling normally, and scrolling with the trackpad option in the pattern editor (the sequencer has no scrolling effect when trackpad-mode is enabled)
![normal-scrolling](https://user-images.githubusercontent.com/433656/91187506-3e342180-e6be-11ea-82b2-6243c307e55e.gif)

**Comment by BleuBleu** [comment]
Ha yes. 

As mentioned in the documentation (https://famistudio.org/doc/config/#user-interface-configuration) track pad controls don't work well on Linux. I almost removed the feature at one point since I have no plans to fix it unfortunately. 

![Capture](https://user-images.githubusercontent.com/6654334/91277727-ca754000-e7b5-11ea-83da-194b4bc9e6d2.PNG)

This is a combination of 2 things: 

1. Gesture controls (pinch to zoom) are not supported natively (unlike MacOS and Windows), so things like pinch-to-zoom wont work.
2. GTK2 : FamiStudio uses an old version of GTK, so its impossible for it to receive "fractional" mouse wheel increment, hence the large "jumps" that you get.

Upgrading to GTK3 would alleviate #2, but it is a huge change, and there are complications, especially regarding the Mac version.  I tried it once and it seemed like it was gonna be too much work.

Very sorry to say, but this will not be fixed anytime soon, unless we find a courageous developer willing to upgrade both the MacOS and Linux version to GTK3.

-Mat

**Comment by BleuBleu** [comment]
Somewhat improved in 4.0.0. There will never be a pinch to zoom for trackpad in Linux since there is no touch gesture support.
