### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jaythomas** [BleuBleu/FamiStudio#42]
It would be great to see (better) ARM64 support. I'm using the Pinebook Pro with Arch Linux Arm. I get to the part where I go to run it and it asks for openal32.dll (which I don't have). I saw in the README mention of using dllmap, but I'm not a mono guy so I don't know where to begin in setting that up.

Aside from dependencies, setup has been painless so thank you for that.

**Comment by BleuBleu** [comment]
Hi! Thanks for reaching out.

Unfortunately, given the almost-non-existant user base on Linux, I dont plan to expand support beyond x64 at this point (even that, support will be limited). All the 4 .so files stipped with FamiStudio are x64, so none of those will work for ARM. The .exe itself will as it is simply .net bytecode that will get jitted by mono on startup.

I'm sure you can fiddle around and make it work, but it will require recompiling all the the .so files for your target platform. 

- The 2 .so that ships with FamiStudio can simply be compiled from source with the little "build_linux.sh" script. 
- For openal and rtmidi, those are standard libraries that you should be able to compile from source or get from your favorite package-distribution system. You may already have openalsoft on your system if you are lucky. You can use a dllmap to point to the correct libs, of grab the .so and rename it to the name that FamiStudio expect. Unfortunately, I am no expert on dllmaps either, the mono documentation is your only resource here.

-Mat

**Comment by jaythomas** [comment]
Thanks for the quick response. Assuming me or someone got it working would you accept a pull request to bring in support or is that a maintenance issue? I'm thinking ARM tablets and the upcoming Macbooks could also benefit and bring in more ARM users besides just the Linux guys and gals. Maybe something to consider in the future.

**Comment by BleuBleu** [comment]
For sure, if there are code changes needed to support more platforms, Il'l grab them.

But i seriously doubt there will be any, 90% of the app is regular C#, which is platform agnostic, and the .so are compiling all 3 platforms already. But I may be wrong. Keep me posted!

-Mat

**Comment by jaythomas** [comment]
Yeah, likely just README updates. Cool, let's close this for now then. Thanks.

**Comment by BleuBleu** [comment]
Cool!

Actually, one thing i hope someone contributes one day would be a proper makefile. Something Linux people can just run and get a fresh build that works for their machine... One day maybe! 🤞 

-Mat
