### ISSUE TITLE
Key bindings don't honor keyboard layout

### ISSUE THREAD

**Issue by jaythomas** [BleuBleu/FamiStudio#44]
It seems the key bindings are bound to the actual keycodes so that whatever keyboard layout I am using (colemak, azerty, etc) it will always bind sliding for instance to the physical key that would be an S in qwerty layout. I've only tested on Linux.

**Comment by BleuBleu** [comment]
Hi! Im not sure if you are the same person who chimed in on discord. Anyhow, as I said to that person i don't know what's the best way to fix this. 

I can think of 2 ways:

1. Somehow auto-detect it, but doing this well on all 3 platforms seems like a nightmare/impossible. Also, I will not be able to test any of it since i only have a US keyboard here. 
2. Allow user to configure every single piano/keyboard key, but this also will be very annoying to users and might create issues if they assign keys that are already bound as shortcut keys but the app. Another issue is that keys are handled completely differently on all 3 platforms and without having the physical keyboard here to map all of them, its going to be very hard to do.

Example of places when i remap keys. These would need to include any exotic keys from every possible keyboard.
https://github.com/BleuBleu/FamiStudio/blob/master/FamiStudio/Source/UI/MacLinux/GtkUtils.cs
https://github.com/BleuBleu/FamiStudio/blob/master/FamiStudio/Source/UI/MacLinux/OpenTkUtils.cs

So I'll keep thinking about it, but until i have a more solid plan, don't expect much movement on this.

In the meantime, its usually easy to have multiple keyboard layouts loaded, you can switch to a QWERTY layout when in FamiStudio.

-Mat

**Comment by jaythomas** [comment]
For what it's worth, I am using a US keyboard with the Colemak layout. Interestingly ctrl+s is mapped to the Colemak S key as expected even though "s" for slide remains mapped to qwerty's S key. (I have not been on any Discord server.)

**Comment by BleuBleu** [comment]
You are right, this is extremely inconsistent and I should at least fix THAT! :) I'll look into it, this is a left over from when i ported from the Mac to the Linux version. Some codepaths uses different ways of reading the keyboard state and that's not great...

-Mat

**Comment by nezvers** [comment]
I have no knowledge of the backend but I'll give an idea.
Allow user to input keys manually, be able to save the settings externally (and load from file). That way those who have different keyboards and willing to help out could make those files be included as presets.

**Comment by BleuBleu** [comment]
This should be much better in 3.0.0. Please reopen if not.
