### ISSUE TITLE
Do not use "#Famitracker text export" as an identify header

### ISSUE THREAD

**Issue by owomomo** [BleuBleu/FamiStudio#47]
If you look into the code of FamiTracker, you'll find the lines starts with `#` in Famitracker text export acturally means it's a line of comment, any changes of comment lines should not affect the importing.
I know there isn't any way to know the version of FamiTracker text export, but this is the initial defect of the format itself, not the responsibility of 3rd party FamiStudio. The best solution is not try to check its version.

**Comment by BleuBleu** [comment]
Hi! 

Thanks for the suggestion, but I will respectfully disagree. Even though it is not technically part of the specs, I will output it and use it to check the version since people are currently getting crashes when opening file generated from 0.5.0 beta for example. Yes, the parsing code could be more robust, but I don't have time to spend on this.

https://github.com/BleuBleu/FamiStudio/commit/9818ca0aa1821fdd41fe8c5df437ef9422fda949

-Mat
