### ISSUE TITLE
Missing documentation for DPCMSample ReverseBits attribute in FamiStudio text export

### ISSUE THREAD

**Issue by jameswilddev** [BleuBleu/FamiStudio#53]
The FamiStudio text export includes a "ReverseBits" boolean in DPCMSample lines:

https://github.com/BleuBleu/FamiStudio/blob/88575e35a93db92745733be6f55a21f60ada2291/FamiStudio/Source/IO/FamistudioTextFile.cs#L34

This isn't listed in the documentation:

https://github.com/BleuBleu/FamiStudio/blob/2.4.0/Docs/docs/importexport.md#format-specification

I can PR to add this; does the same apply here as in the NSF?

https://github.com/BleuBleu/FamiStudio/blob/2.4.0/Docs/docs/importexport.md#nintendo-sound-format-1

**Comment by BleuBleu** [comment]
Sure! Go ahead. You're on fire! I tend to work very fast and I sometimes forget little things like this :) 

If its not too much to ask, do you think you could do this in the 2.4.0 branch (btw dont use this branch for your daily music composition!!! its a mess! :)) Otherwise we can always re-base the PR.

Also, this is 100% optional, feel free to jump on the discord in the #development channel, might be easier to talk.

-Mat

**Comment by jameswilddev** [comment]
Got it thanks!  

So some background if you're curious: I've been using FamiStudio for about a week now, really like it and written some music in it.  I'm currently writing an importer for its text format for my game engine which is why I'm scrutinizing this aspect of it a little bit.  Probably come across a bit as nitpicking, but if it wasn't this good in the first place I wouldn't be sanding the last few sharp edges!  Thanks for FamiStudio.

**Comment by BleuBleu** [comment]
Awesome!!! Don't worry, I can tell when people are nitpicking and when people are being constructive and want to move things forward. :)

-Mat
