### ISSUE TITLE
Document: for FamiTracker import, pitch envelopes do not affect noise

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#64]
In FamiTracker a pitch envelope can affect noise in the same way that arpeggios do. Since FamiStudio does not replicate this behaviour, it would be helpful to note that limitation in the docs.

**Comment by BleuBleu** [comment]
Hi!

Ill be honest i did not know that the pitch envelope could have an impact on the noise channel. Arpeggio envelope seemed to make more sense to me since the noise channel only has a handful of discrete steps.

Ill take a look over the weekend. If its easy to implement and doesn't feel to "FamiTracker-specific" ill implement it, otherwise ill update the doc to say its not supported.

-Mat

**Comment by BleuBleu** [comment]
Doc was updated a while ago. Closing. Will look into adding real support for this in the future tho.
