### ISSUE TITLE
Feature request: Add a beat highlight divider and bar number for each beat (or 1/n) of the piano roll

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#8]
This feature comes from FL Studio and helps to write the correct note length without having to modify it repeatedly.
![Snipaste_2020-04-12_05-56-17](https://user-images.githubusercontent.com/48104960/79055809-70e6fb80-7c82-11ea-82c6-f6065b265aec.png)

**Comment by BleuBleu** [comment]
Hello! 

Thats not a bad idea. Im in the process of wrapping up the next version, so I'm limiting the amount of "new stuff" I put in order to stabilise. But I'll see what I can do.

One thing that should also help in the next release is that you will be able to drag notes as you add them (like in FL Studio). I found that this cut down on the amount of mistakes I make (and frustration).

-Mat
