### ISSUE TITLE
MIDI import doesn't work properly with N163 expansion

### ISSUE THREAD

**Issue by Epictyphlosion** [BleuBleu/FamiStudio#81]
When selecting the Namco 163 expansion in the MIDI import window, it automatically assigns all eight channels on the expansion chip. Once the MIDI is imported, however, only one expansion channel is used. 

Setting the number of channels to 8 in the song properties menu before or after importing doesn't work around this.

**Comment by BleuBleu** [comment]
Thanks for reaching out!

I'm on my phone, but I'm 99% sure you are right. I'll change it so that it sets the number of n163 channels based on how many you assign in that grid in the MIDI import dialog. 

I'll include this in the next hotfix release (3.0.2) which should be in ~2w. Waiting for more bugs to be reported!

-Mat

**Comment by BleuBleu** [comment]
Fixed in 3.0.2
