### ISSUE TITLE
Feature Request - OGG export

### ISSUE THREAD

**Issue by Metlmeta** [BleuBleu/FamiStudio#82]
In addition to MP3 and WAV export, having the ability to export .ogg files would be super useful. A few game engines use OGG as the default music file format since it has a smaller file size and can seamlessly loop, so being able to natively export to this format would be a great workflow improvement.

Thank you for all your hard work!

**Comment by BleuBleu** [comment]
Hi!

I definitely thought about this, but since we already had 2 formats (WAV/MP3), this was never really a priority. Ill see how hard it is to do. If you happen to know any small/self-contained/open-source libraries that encode to OGG let me know, that could help cut down on the research i need to do.

In the meantime, if you need to export to OGG a lot, maybe creating yourself a little console command script that exports to wav, then converts to OGG might be helpful? 

-Mat

**Comment by Metlmeta** [comment]
Thanks for the reply! This library looks like it could be useful: https://github.com/SteveLillis/.NET-Ogg-Vorbis-Encoder

In the meantime, I think a script would be a good idea. 👍

**Comment by danielpiron** [comment]
ffmpeg? Or would that be way too much heft?

**Comment by BleuBleu** [comment]
I ended up using libvorbis directly. It will be coming out sometimes in august, likely towards the end.

![image](https://user-images.githubusercontent.com/6654334/125014963-334d6a00-e0a1-11eb-8a83-c274e36bcdfe.png)

**Comment by Metlmeta** [comment]
That's awesome!! Thanks so much for the effort you put in. I look forward to it!

**Comment by BleuBleu** [comment]
Done in 3.1.0.
