### ISSUE TITLE
Bug Report:Corrupted Sound from Imported Famitracker Module.

### ISSUE THREAD

**Issue by KeitoTobi1** [BleuBleu/FamiStudio#92]
When I imported this Famitracker module file, the song went wrong.
[Hummer Takes Over.zip](https://github.com/BleuBleu/FamiStudio/files/7229511/Hummer.Takes.Over.zip)

**Comment by BleuBleu** [comment]
I'm gonna need more detail to work on this. What is wrong, etc. 

-Mat

**Comment by KeitoTobi1** [comment]
Originally, the same sound as "Correct.wav" in the archive should be played, but
When imported into FamiStudio, the same sound as "Wrong.wav" in the archive will be played.
[Correct And Wrong.zip](https://github.com/BleuBleu/FamiStudio/files/7230988/Correct.And.Wrong.zip)

**Comment by BleuBleu** [comment]
Thanks, ill try to take a look for the next major release. Seems like a slide note (1xx/2xx/3xx/Qxx/Rxx) going crazy!

-Mat

**Comment by BleuBleu** [comment]
Hi!

Thanks for you patience. I finally had a time to look into this. The issue comes with the way FamiTracker vs. FamiStudio handles pitch and arpeggio envelopes. FamiStudio does those a bit differently.

Long story short: Your module uses a looping arpeggio on a few instruments to prevent the pitch envelopes from drifting. FamiStudio does not need this hack as it supports "Absolute" pitch envelope, where the pitch value that you draw is the one that will be used, without adding the previous values. 

I will add a warning in the upcoming version to make you aware of this when importing a FTM that has this issue, and I will make sure the documentation is clearer about this so you know what to fix when importing those. 

https://famistudio.org/doc/import/#famitracker-text-or-binary

In the meantime, here is a fixed version of your module, it took me 1 minute to fix everything. I simply changed the envelopes from Relative to absolute for those instruments. 

[HummerFixed.zip](https://github.com/BleuBleu/FamiStudio/files/7298540/HummerFixed.zip)

-Mat

**Comment by BleuBleu** [comment]
Fixed in 3.2.0.
