### ISSUE TITLE
Bug report: Importing a certain midi does not work

### ISSUE THREAD

**Issue by P-Star7** [BleuBleu/FamiStudio#97]
When trying to import this .mid (original by Studio Pixel, converted from .org to .mid and combined some channels by me)
[Running Hell 8bit.zip](https://github.com/BleuBleu/FamiStudio/files/7491781/Running.Hell.8bit.zip)

Error message:
Error: Object reference not set to an instance of an object.
Error:    at FamiStudio.MidiFileReader.CreatePatterns(List`1& patternInfos, Int32 measuresPerPattern) in C:\Users\bleub\Documents\GitHub\FamiStudio\FamiStudio\Source\IO\MidiFile.cs:line 878
   at FamiStudio.MidiFileReader.Load(String filename, Int32 expansion, Boolean pal, MidiSource[] channelSources, Boolean velocityAsVolume, Int32 polyphony, Int32 measuresPerPattern) in C:\Users\bleub\Documents\GitHub\FamiStudio\FamiStudio\Source\IO\MidiFile.cs:line 1134

**Comment by BleuBleu** [comment]
Hi! 

Thanks for the detailed report. I've identified the issue and will include it in the next version. You are very lucky since its coming out in about a week, so you wont have to wait too long.

If you want a workaround in the meantime, the first measure seem to contain multiple non-sensical tempo changes (to 6666 for example). Deleting those should fix the issue.

-Mat

**Comment by BleuBleu** [comment]
Fixed in 3.2.0.
